### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by wolflord212312** [NoName-31/Honeygain-bot#1]
C:\Users\talon\Downloads\Honeygain-bot-main\honeygain-bot\node_modules\discord.js\src\rest\APIRequest.js:34
    agent ??= new https.Agent({ ...this.client.options.http.agent, keepAlive: true });
          ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\talon\Downloads\Honeygain-bot-main\honeygain-bot\node_modules\discord.js\src\rest\RESTManager.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by wolflord212312** [comment]
[2022-01-13T07_06_10_260Z-debug.log](https://github.com/NoName-31/Honeygain-bot/files/7860674/2022-01-13T07_06_10_260Z-debug.log)

**Comment by NoName-31** [comment]
use nodejs16
